spring.application.name=Eduplay-Application

#Database config
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/zonacerdas}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:manman}

# Driver HikariCP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Hibernate
spring.jpa.hibernate.ddl-auto=update

# DB Migration Config
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=false

#JWT Config
jwt.secret=${JWT_SECRET:secret-key-local-very-aman-banget-parah-amannya}
# Access Token Lifetime - 1 Hour (Milisecond)
jwt.expiration=3600000