spring.application.name=Eduplay-Application

#Connection Database (Postgresql) - (LOCALHOOST)
spring.datasource.url=jdbc:postgresql://localhost:5432/eduplay
spring.datasource.username=postgres
spring.datasource.password=manman

#DB Migration Configuration (Eksekutor DB Structure)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
